### ISSUE TITLE
Hang when splitting pages from a particular PDF

### ISSUE THREAD

**Issue by direvus** [mstamy2/PyPDF2#165]
I have a 4-page PDF here, which seems to render just fine as a whole, but when I try to pull any individual page out, and write it as a new PDF with PdfFileWriter, it hangs forever.  It seems that it is getting stuck trying to resolve indirect references.  I'm afraid I cannot provide the PDF itself, but I would be happy to answer any questions regarding its structure.

I have used PyPDF2 across a great many documents and this is the only case I know of that exhibits this problem.  I'm currently using version 1.23 from pip.

    ^CTraceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 315, in write
        self._sweepIndirectReferences(externalReferenceMap, self._root)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
        self._sweepIndirectReferences(externMap, realdata)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
        value = self._sweepIndirectReferences(externMap, value)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
        self._sweepIndirectReferences(externMap, realdata)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
        value = self._sweepIndirectReferences(externMap, value)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 389, in _sweepIndirectReferences
        value = self._sweepIndirectReferences(externMap, data[i])
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
        self._sweepIndirectReferences(externMap, realdata)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
        value = self._sweepIndirectReferences(externMap, value)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 409, in _sweepIndirectReferences
        newobj = data.pdf.getObject(data)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 1360, in getObject
        retval = self._getObjectFromStream(indirectReference)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/pdf.py", line 1333, in _getObjectFromStream
        obj = readObject(streamData, self)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 95, in readObject
        return NumberObject.readFromStream(stream)
      File "/usr/local/lib/python2.7/dist-packages/PyPDF2/generic.py", line 259, in readFromStream
        m = NumberObject.NumberPattern.search(tok)
    KeyboardInterrupt

Not sure if this will help, but here are the dicts for each of the pages from the source PDF:

    {'/Contents': IndirectObject(8, 0),
     '/CropBox': [0, 0, 595.68000, 842.40000],
     '/MediaBox': [0, 0, 595.68000, 842.40000],
     '/Parent': IndirectObject(1, 0),
     '/Resources': {'/ProcSet': ['/PDF', '/ImageB'],
                    '/XObject': {'/Im25': IndirectObject(31, 0)}},
     '/Rotate': IndirectObject(34, 0),
     '/Type': '/Page'}

    {'/Contents': IndirectObject(2, 0),
     '/CropBox': [0, 0, 595.68000, 842.40000],
     '/MediaBox': [0, 0, 595.68000, 842.40000],
     '/Parent': IndirectObject(1, 0),
     '/Resources': {'/ProcSet': ['/PDF', '/ImageB'],
                    '/XObject': {'/Im2': IndirectObject(3, 0)}},
     '/Rotate': IndirectObject(18, 0),
     '/Type': '/Page'}

    {'/Contents': IndirectObject(5, 0),
     '/CropBox': [0, 0, 595.68000, 842.40000],
     '/MediaBox': [0, 0, 595.68000, 842.40000],
     '/Parent': IndirectObject(1, 0),
     '/Resources': {'/ProcSet': ['/PDF', '/ImageC'],
                    '/XObject': {'/Im8': IndirectObject(7, 0)}},
     '/Rotate': IndirectObject(19, 0),
     '/Type': '/Page'}

    {'/Contents': IndirectObject(5, 0),
     '/CropBox': [0, 0, 595.68000, 842.40000],
     '/MediaBox': [0, 0, 595.68000, 842.40000],
     '/Parent': IndirectObject(1, 0),
     '/Resources': {'/ProcSet': ['/PDF', '/ImageB'],
                    '/XObject': {'/Im14': IndirectObject(11, 0)}},
     '/Rotate': IndirectObject(20, 0),
     '/Type': '/Page'}

**Comment by cryptid11** [comment]
When will be enabled this "go no if you find dangling references" feature?

**Comment by direvus** [comment]
I can confirm that this issue is resolved as of PyPDF2 1.25.1.  Splitting a page out of these PDFs now raises a PdfReadWarning, which can easily be caught and ignored.
