### ISSUE TITLE
AttributeError: 'str' object has no attribute 'seek'

### ISSUE THREAD

**Issue by akaiame** [mstamy2/PyPDF2#170]
I just upgraded my system to python 3.4.2 and PyPDF2 1.24 and am trying to port my code over. I ran into this error:

Traceback (most recent call last):
  File "C:\cms_software\pdf_replica\PdfZipRecipe.py", line 863, in check_for_multiple_page_pdf
    input_pdf = PdfFileReader(open(pdf_path, "rb"), strict=False)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 913, in __init__
    self.read(stream)
  File "C:\Python34\lib\site-packages\PyPDF2\pdf.py", line 1462, in read
    stream.seek(-1, 2)
  File "C:\Python34\lib\site-packages\django\core\files\utils.py", line 20, in <lambda>
    seek = property(lambda self: self.file.seek)
AttributeError: 'str' object has no attribute 'seek'

This is the line that the error is caused by:

input_pdf = PdfFileReader(open(pdf_path, "rb"), strict=False)

I saw a similar issue that was solved for python 2.7, but no comments on this happening with python 3. Is there something I've missed?

**Comment by akaiame** [comment]
There were a few places where I didn't change file() to open() when porting my code. Sorry!
