### ISSUE TITLE
readStringFromStream fails reading token with a valid pdf

### ISSUE THREAD

**Issue by dellelce** [mstamy2/PyPDF2#175]
I am just  starting with the pypdf2 library for extracting metadata from a series of books, and with the very first I get this:

Traceback (most recent call last):
  File "docinfo.py", line 18, in <module>
    pdf = PdfFileReader(open(fname, 'rb'))
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/pdf.py", line 913, in **init**
    self.read(stream)
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/pdf.py", line 1577, in read
    xrefstream = readObject(stream, self)
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/generic.py", line 65, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/generic.py", line 564, in readFromStream
    value = readObject(stream, pdf)
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/generic.py", line 70, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/generic.py", line 165, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/generic.py", line 76, in readObject
    return readStringFromStream(stream)
  File "/cygdrive/c/data/src/languages/pdf/examples/PyPDF2/generic.py", line 376, in readStringFromStream
    raise utils.PdfReadError("Unexpected escaped string:" + str(tok) + " after reading: " + str(txt))
PyPDF2.utils.PdfReadError: Unexpected escaped string:+ after reading: Y˜§‘ÐH202è;jiF„]/Compress<</SpecO/1.4/LengthO 4605698>>/Info 2441 0 R/Size 3163/Length 9173>>stream
xÚ-šy|ÔÕ½þó@B $B²OfŸ    ‚"ŠàßýœAQ„Š(_îŠ¬î
Ÿ]…ªªF9Pí½<T—ƒ)Õ¨B¬ËJ-¥U­ë…¡”zT¥OÑå0T•þ,7Uo“k@Õ¡—ª£'×ˆ_ß}nª*¿ª…çË5£êÔár£Pµô¹Ñ¨ºð[r-¨Zs¢ÜT]{œ

I slightly modified readStringFromStream to show more information in the exception message.

**Comment by fgeek** [comment]
@dellelce Could you include PDF file to this bug report or send it to me privately, thank you. What version did you use when you noticed this error?

**Comment by MartinThoma** [comment]
As this is impossible to reproduce and to hard to narrow down without code / PDF, I'll close it.
