### ISSUE TITLE
OCRMyPDF - AttributeError: 'ArrayObject' object has no attribute 'getData'

### ISSUE THREAD

**Issue by tuxasus** [mstamy2/PyPDF2#220]
Hey, I am trying to get OCRmyPDF running on some PDFs generated / archived using my scanner. So far the program should run, but when I try to run it on an existing PDF (freshly scanned) I get the following error message:

[code]
/usr/lib/python3/dist-packages/pkg_resources.py:1031: UserWarning: /home/florian/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/ocrmypdf", line 9, in <module>
    load_entry_point('ocrmypdf==3.0rc4', 'console_scripts', 'ocrmypdf')()
  File "/usr/local/lib/python3.4/dist-packages/ocrmypdf-3.0rc4-py3.4.egg/ocrmypdf/main.py", line 848, in run_pipeline
    cmdline.run(options)
  File "/usr/local/lib/python3.4/dist-packages/ruffus-2.6.3-py3.4.egg/ruffus/cmdline.py", line 824, in run
    **appropriate_options)
  File "/usr/local/lib/python3.4/dist-packages/ruffus-2.6.3-py3.4.egg/ruffus/task.py", line 5938, in pipeline_run
    raise job_errors
ruffus.ruffus_exceptions.RethrownJobError: 

Original exception:

    Exception #1
      'builtins.AttributeError('ArrayObject' object has no attribute 'getData')' raised in ...
       Task = def ocrmypdf.main.repair_pdf(...):
       Job  = [source.pdf -> .../com.github.ocrmypdf.gao5vxz1/source.repaired.pdf, <ocrmypdf.main.WrappedLogger>, [], <_thread.lock>]
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/ruffus-2.6.3-py3.4.egg/ruffus/task.py", line 751, in run_pooled_job_without_exceptions
        register_cleanup, touch_files_only)
      File "/usr/local/lib/python3.4/dist-packages/ruffus-2.6.3-py3.4.egg/ruffus/task.py", line 567, in job_wrapper_io_files
        ret_val = user_defined_work_func(*params)
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf-3.0rc4-py3.4.egg/ocrmypdf/main.py", line 332, in repair_pdf
        pdfinfo.extend(pdf_get_all_pageinfo(output_file))
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf-3.0rc4-py3.4.egg/ocrmypdf/pageinfo.py", line 137, in pdf_get_all_pageinfo
        return [_pdf_get_pageinfo(infile, n) for n in range(pdf.numPages)]
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf-3.0rc4-py3.4.egg/ocrmypdf/pageinfo.py", line 137, in <listcomp>
        return [_pdf_get_pageinfo(infile, n) for n in range(pdf.numPages)]
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf-3.0rc4-py3.4.egg/ocrmypdf/pageinfo.py", line 118, in _pdf_get_pageinfo
        if _page_has_inline_images(page):
      File "/usr/local/lib/python3.4/dist-packages/ocrmypdf-3.0rc4-py3.4.egg/ocrmypdf/pageinfo.py", line 45, in _page_has_inline_images
        data = contents.getData()
    AttributeError: 'ArrayObject' object has no attribute 'getData' 
[/code]

It doesn't matter which scanned file I use, as an example I attached a file printed and scanned from liquidweb  
![source](https://cloud.githubusercontent.com/assets/13709851/9151473/df98763e-3e03-11e5-8c19-39843f1808e0.png)

**Comment by dhudson1** [comment]
I think that you meant to post the issue <a href="https://github.com/fritz-hh/OCRmyPDF">here</a>.

This particular page is only for issues with PyPDF2.

**Comment by claird** [comment]
Hello,

Thank you for your question, comments, and/or concerns regarding PyPDF2.
All of our PyPDF2 users are very important to us.  Unfortunately at this
present time we are in the process of regrouping our office.  Your
questions are very important to us but regretfully we will not be able to
address any issues regarding PyPDF2 until later this fall.  However, if
this is an urgent matter and you need immediate assistance please respond
to this email and we will try our best to accommodate your needs sooner.
My apologies for the inconvenience.  Thank you for your patience.

Sincerely,

Selma Kishwar

Phaseit, Inc.

selmaikishwar@gmail.com

**Comment by fire17** [comment]
7 years later still with this error
